name: build-and-test

on:
  push:
  workflow_dispatch:

env:
  LIBERICA_URL: https://download.bell-sw.com/java/11.0.16.1+1/bellsoft-jdk11.0.16.1+1-linux-amd64-full.tar.gz

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: liberica@17=tgz+${{ env.LIBERICA_URL }}
      - run: sbt -v update compile
      - run: sbt -v test
